version: '3.9'

services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile
    command: gunicorn langer.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/usr/src/app/staticfiles/
      - media_volume:/usr/src/app/mediafiles/
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db


  db:
    image: postgres:14-alpine

    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db

  nginx:
    restart: always
    build: ./nginx
    volumes:
      - static_volume:/usr/src/app/staticfiles/
      - media_volume:/usr/src/app/mediafiles/
    ports:
      - 1337:80
    depends_on:
      - web


  pgadmin:
    user: root
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "test@test.test"
      PGADMIN_DEFAULT_PASSWORD: "test"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5050:80"
    restart: unless-stopped





volumes:
  postgres_data:
  static_volume:
  media_volume:

