# Generated by Django 4.1.2 on 2023-04-19 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dictionary', '0029_rename_language_id_cardgroup_language_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10, verbose_name='Символ')),
                ('transcription', models.CharField(max_length=10, verbose_name='транскрипция')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='dictionary.language', verbose_name='язык')),
            ],
        ),
        migrations.CreateModel(
            name='LetterGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letters', models.ManyToManyField(to='alphabet.letter')),
            ],
        ),
    ]
