# Generated by Django 4.1.2 on 2023-04-20 09:31

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Alphabet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, verbose_name="Название")),
                ("one_dimension", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="AlphabetEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lang_index_column", models.IntegerField()),
                ("lang_index_row", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Letter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=10, verbose_name="Символ")),
                (
                    "transcription",
                    models.CharField(max_length=10, verbose_name="транскрипция"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LetterGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Название")),
                ("letters", models.ManyToManyField(to="alphabet.letter")),
            ],
        ),
    ]
