# Generated by Django 4.1.2 on 2023-04-19 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alphabet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lettergroup',
            name='name',
            field=models.CharField(default='test', max_length=50, verbose_name='Название'),
            preserve_default=False,
        ),
    ]
