# Generated by Django 4.1.2 on 2023-04-20 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("dictionary", "0001_initial"),
        ("alphabet", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="letter",
            name="language",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                to="dictionary.language",
                verbose_name="язык",
            ),
        ),
        migrations.AddField(
            model_name="alphabetentry",
            name="alphabet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                to="alphabet.alphabet",
                verbose_name="алфавит",
            ),
        ),
        migrations.AddField(
            model_name="alphabetentry",
            name="letter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                to="alphabet.letter",
                verbose_name="язык",
            ),
        ),
        migrations.AddField(
            model_name="alphabet",
            name="language",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                to="dictionary.language",
                verbose_name="язык",
            ),
        ),
    ]
