# Generated by Django 4.1.2 on 2023-04-19 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alphabet', '0002_lettergroup_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alphabet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='AlphabetEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang_index_row', models.IntegerField()),
                ('lang_index_column', models.IntegerField()),
                ('alphabet', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='alphabet.alphabet', verbose_name='алфавит')),
                ('letter', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='alphabet.letter', verbose_name='язык')),
            ],
        ),
    ]
