# Generated by Django 4.1.2 on 2023-04-19 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alphabet', '0003_alphabet_alphabetentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='alphabet',
            name='one_dimension',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='alphabetentry',
            name='lang_index_row',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
