# Generated by Django 4.1.2 on 2023-04-19 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0029_rename_language_id_cardgroup_language_and_more'),
        ('alphabet', '0004_alphabet_one_dimension_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alphabet',
            name='language',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='dictionary.language', verbose_name='язык'),
            preserve_default=False,
        ),
    ]
