# Generated by Django 4.1.2 on 2023-04-21 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CardGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=300, verbose_name="группа")),
                (
                    "is_public",
                    models.BooleanField(default=False, verbose_name="доступна всем"),
                ),
            ],
            options={
                "verbose_name": "подборка",
                "verbose_name_plural": "подборки",
            },
        ),
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Название")),
                (
                    "flag_code",
                    models.CharField(max_length=2, null=True, verbose_name="Код"),
                ),
                (
                    "emoji",
                    models.CharField(
                        blank=True,
                        max_length=3,
                        null=True,
                        verbose_name="Эмоджи (для фронта)",
                    ),
                ),
            ],
            options={
                "verbose_name": "язык",
                "verbose_name_plural": "языки",
            },
        ),
        migrations.CreateModel(
            name="Word",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.CharField(max_length=150, verbose_name="Слово или фраза"),
                ),
            ],
            options={
                "verbose_name": "cлово",
                "verbose_name_plural": "cлова",
            },
        ),
        migrations.CreateModel(
            name="WordCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transcription",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="транскрипция",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=300, null=True, verbose_name="значение"
                    ),
                ),
                (
                    "example",
                    models.CharField(
                        blank=True,
                        max_length=300,
                        null=True,
                        verbose_name="пример использования",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(default=False, verbose_name="доступна всем"),
                ),
            ],
            options={
                "verbose_name": "карточка",
                "verbose_name_plural": "карточки",
            },
        ),
        migrations.CreateModel(
            name="WordCardProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "score",
                    models.IntegerField(
                        default=0, verbose_name="знание словарной карточки (0..10)"
                    ),
                ),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dictionary.wordcard",
                        verbose_name="карточка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Прогресс",
                "verbose_name_plural": "Прогрессы",
            },
        ),
    ]
