# Generated by Django 4.1.2 on 2023-04-21 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("userprofile", "0001_initial"),
        ("dictionary", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="wordcardprogress",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="userprofile.userprofile",
            ),
        ),
        migrations.AddField(
            model_name="wordcard",
            name="card_groups",
            field=models.ManyToManyField(
                blank=True,
                related_name="wordcards",
                to="dictionary.cardgroup",
                verbose_name="словарные группы",
            ),
        ),
        migrations.AddField(
            model_name="wordcard",
            name="owner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wordcards",
                to="userprofile.userprofile",
                verbose_name="создатель",
            ),
        ),
        migrations.AddField(
            model_name="wordcard",
            name="translation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="translation_cards",
                to="dictionary.word",
                verbose_name="перевод",
            ),
        ),
        migrations.AddField(
            model_name="wordcard",
            name="used_by",
            field=models.ManyToManyField(
                blank=True,
                related_name="shared_wordcards",
                to="userprofile.userprofile",
            ),
        ),
        migrations.AddField(
            model_name="wordcard",
            name="word",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="word_cards",
                to="dictionary.word",
                verbose_name="слово или фраза",
            ),
        ),
        migrations.AddField(
            model_name="word",
            name="language",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="dictionary.language",
                verbose_name="язык",
            ),
        ),
        migrations.AddField(
            model_name="cardgroup",
            name="language",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="dictionary.language",
            ),
        ),
        migrations.AddField(
            model_name="cardgroup",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="card_groups",
                to="userprofile.userprofile",
                verbose_name="создатель",
            ),
        ),
        migrations.AddField(
            model_name="cardgroup",
            name="used_by",
            field=models.ManyToManyField(
                blank=True,
                related_name="shared_cardgroups",
                to="userprofile.userprofile",
            ),
        ),
    ]
