# Generated by Django 4.1.2 on 2023-05-06 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    atomic = True
    dependencies = [
        ('userprofile', '0001_initial'),
        ('dictionary', '0002_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WordCardProgress',
            new_name='CardProgress',
        ),
        migrations.RenameModel(
            old_name='WordCard',
            new_name='Card',
        ),
        migrations.RenameModel(
            old_name='CardGroup',
            new_name='Deck',
        ),

        migrations.RenameField(
            model_name='card',
            old_name='card_groups',
            new_name='decks'
        ),
        migrations.AlterField(
            model_name='card',
            name='decks',
            field=models.ManyToManyField(blank=True, related_name='cards', to='dictionary.deck',
                                         verbose_name='словарные группы'),
        ),
        migrations.AlterField(
            model_name='card',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards',
                                    to='userprofile.userprofile', verbose_name='создатель'),
        ),
        migrations.AlterField(
            model_name='card',
            name='translation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translation_cards',
                                    to='dictionary.word', verbose_name='перевод'),
        ),
        migrations.AlterField(
            model_name='card',
            name='used_by',
            field=models.ManyToManyField(blank=True, related_name='shared_cards', to='userprofile.userprofile'),
        ),
        migrations.AlterField(
            model_name='card',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards',
                                    to='dictionary.word', verbose_name='слово или фраза'),
        ),
        migrations.AlterField(
            model_name='cardprogress',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.card',
                                    verbose_name='карточка'),
        ),

    ]
