# Generated by Django 4.1.2 on 2023-05-11 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
        ('dictionary', '0003_card_deck_remove_wordcard_card_groups_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deck',
            options={'verbose_name': 'колода', 'verbose_name_plural': 'колоды'},
        ),
        migrations.AlterField(
            model_name='deck',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='decks', to='userprofile.userprofile', verbose_name='создатель'),
        ),
        migrations.AlterField(
            model_name='deck',
            name='used_by',
            field=models.ManyToManyField(blank=True, related_name='shared_decks', to='userprofile.userprofile'),
        ),
        migrations.AlterField(
            model_name='language',
            name='emoji',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Эмоджи (для фронта)'),
        ),
    ]
