# Generated by Django 4.1.2 on 2022-10-28 19:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("dictionary", "0008_wordcardprogress_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="cardgroup",
            name="is_public",
            field=models.BooleanField(default=False, verbose_name="доступна всем"),
        ),
        migrations.AddField(
            model_name="cardgroup",
            name="owner",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="wordcard",
            name="is_public",
            field=models.BooleanField(default=True, verbose_name="доступна всем"),
        ),
    ]
