# Generated by Django 4.1.2 on 2022-11-10 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("dictionary", "0009_cardgroup_is_public_cardgroup_owner_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="wordcardprogress",
            name="count",
            field=models.IntegerField(default=0, verbose_name="количество тренировок"),
        ),
        migrations.AlterField(
            model_name="cardgroup",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="создатель",
            ),
        ),
        migrations.AlterField(
            model_name="wordcardprogress",
            name="card",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="dictionary.wordcard",
                verbose_name="карточка",
            ),
        ),
        migrations.AlterField(
            model_name="wordcardprogress",
            name="score",
            field=models.FloatField(
                default=0, verbose_name="процент правильных ответов [0..1]"
            ),
        ),
        migrations.AlterField(
            model_name="wordcardprogress",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="пользователь",
            ),
        ),
    ]
