# Generated by Django 4.1.2 on 2023-01-05 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0010_wordcardprogress_count_alter_cardgroup_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='emoji',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='Эмоджи (для фронта)'),
        ),
    ]
