# Generated by Django 4.1.2 on 2023-01-05 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0012_userprofile_alter_wordcard_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordcardprogress',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dictionary.userprofile', verbose_name='пользователь'),
        ),
    ]
