# Generated by Django 4.1.2 on 2023-03-20 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0015_alter_language_emoji'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='transcription',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='транскрипция'),
        ),
    ]
