# Generated by Django 4.1.2 on 2023-03-25 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0016_word_transcription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='default_language',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='word',
            name='transcription',
        ),
        migrations.AddField(
            model_name='wordcard',
            name='transcription',
            field=models.CharField(default='', max_length=255, verbose_name='транскрипция'),
        ),
    ]
