# Generated by Django 4.1.2 on 2023-03-25 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0003_alter_wordcardtraining_user'),
        ('dictionary', '0017_remove_userprofile_default_language_and_more'),
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardgroup',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.userprofile', verbose_name='создатель'),
        ),
        migrations.AlterField(
            model_name='wordcard',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userprofile.userprofile', verbose_name='создатель'),
        ),
        migrations.AlterField(
            model_name='wordcardprogress',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userprofile.userprofile', verbose_name='пользователь'),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
