# Generated by Django 4.1.2 on 2023-03-25 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0019_alter_wordcard_transcription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardgroup',
            name='cards',
            field=models.ManyToManyField(blank=True, null=True, to='dictionary.wordcard', verbose_name='карточки'),
        ),
        migrations.AlterField(
            model_name='wordcard',
            name='transcription',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='транскрипция'),
        ),
    ]
