# Generated by Django 4.1.2 on 2023-04-01 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0021_remove_cardgroup_cards_wordcard_card_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardgroup',
            name='language_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dictionary.language'),
        ),
        migrations.AlterField(
            model_name='wordcard',
            name='card_groups',
            field=models.ManyToManyField(blank=True, to='dictionary.cardgroup', verbose_name='словарные группы'),
        ),
    ]
