# Generated by Django 4.1.2 on 2023-04-01 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0022_cardgroup_language_id_alter_wordcard_card_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wordcardprogress',
            name='user',
        ),
    ]
