# Generated by Django 4.1.2 on 2023-04-01 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
        ('dictionary', '0023_remove_wordcardprogress_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordcardprogress',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userprofile.userprofile'),
        ),
        migrations.AlterField(
            model_name='wordcard',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='доступна всем'),
        ),
    ]
