# Generated by Django 4.1.2 on 2023-04-01 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
        ('dictionary', '0024_wordcardprogress_user_alter_wordcard_is_public'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wordcardprogress',
            old_name='user',
            new_name='owner',
        ),
        migrations.RemoveField(
            model_name='cardgroup',
            name='owner',
        ),
        migrations.AddField(
            model_name='cardgroup',
            name='owner',
            field=models.ManyToManyField(to='userprofile.userprofile', verbose_name='создатель'),
        ),
    ]
