# Generated by Django 4.1.2 on 2023-04-01 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
        ('dictionary', '0026_wordcard_used_by_alter_cardgroup_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardgroup',
            name='used_by',
            field=models.ManyToManyField(related_name='shared_cardgroups', to='userprofile.userprofile'),
        ),
    ]
