# Generated by Django 4.1.2 on 2023-04-01 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
        ('dictionary', '0027_cardgroup_used_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardgroup',
            name='owner',
        ),
        migrations.AlterField(
            model_name='wordcard',
            name='card_groups',
            field=models.ManyToManyField(blank=True, related_name='wordcards', to='dictionary.cardgroup', verbose_name='словарные группы'),
        ),
        migrations.AddField(
            model_name='cardgroup',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='card_groups', to='userprofile.userprofile', verbose_name='создатель'),
            preserve_default=False,
        ),
    ]
