# Generated by Django 4.1.2 on 2023-04-04 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
        ('dictionary', '0028_remove_cardgroup_owner_alter_wordcard_card_groups_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardgroup',
            old_name='language_id',
            new_name='language',
        ),
        migrations.AlterField(
            model_name='cardgroup',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='card_groups', to='userprofile.userprofile', verbose_name='создатель'),
        ),
        migrations.AlterField(
            model_name='cardgroup',
            name='used_by',
            field=models.ManyToManyField(blank=True, related_name='shared_cardgroups', to='userprofile.userprofile'),
        ),
        migrations.AlterField(
            model_name='wordcard',
            name='used_by',
            field=models.ManyToManyField(blank=True, related_name='shared_wordcards', to='userprofile.userprofile'),
        ),
    ]
