# Generated by Django 4.1.2 on 2022-10-20 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dictionary", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="language",
            options={"verbose_name": "язык", "verbose_name_plural": "языки"},
        ),
        migrations.AlterModelOptions(
            name="word",
            options={"verbose_name": "cлово", "verbose_name_plural": "cлова"},
        ),
        migrations.AlterModelOptions(
            name="wordcard",
            options={"verbose_name": "карточка", "verbose_name_plural": "карточки"},
        ),
        migrations.CreateModel(
            name="CardGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=300, verbose_name="группа")),
                (
                    "cards",
                    models.ManyToManyField(
                        to="dictionary.wordcard", verbose_name="карточки"
                    ),
                ),
            ],
        ),
    ]
