# Generated by Django 4.1.2 on 2022-10-20 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dictionary", "0003_alter_cardgroup_options_wordcardprogress"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="wordcardprogress",
            options={"verbose_name": "Прогресс", "verbose_name_plural": "Прогрессы"},
        ),
    ]
