# Generated by Django 4.1.2 on 2022-10-28 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dictionary", "0006_wordcard_is_public_wordcard_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wordcardprogress",
            name="score",
            field=models.FloatField(
                default=0, verbose_name="прогресс изучения от 0 до 1"
            ),
        ),
    ]
