# Generated by Django 4.1.2 on 2023-03-20 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dictionary', '0016_word_transcription'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordCardTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=150)),
                ('WordCard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.wordcard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.userprofile')),
            ],
        ),
    ]
