# Generated by Django 4.1.2 on 2023-03-20 22:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wordcardtraining',
            old_name='WordCard',
            new_name='wordcard',
        ),
        migrations.AddField(
            model_name='wordcardtraining',
            name='onetime',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='wordcardtraining',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
