# Generated by Django 4.1.2 on 2023-03-25 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
        ('trainings', '0002_rename_wordcard_wordcardtraining_wordcard_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordcardtraining',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.userprofile'),
        ),
    ]
